<a href="https://colab.research.google.com/github/punithpunii/Python/blob/Numpy_Problems/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [17]:
import numpy as np
list1 = [12.23, 13.32, 100, 36.32]
arr1=np.array(list1)
print(arr1.shape)
print(arr1)


(4,)
[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [16]:
arr2 = np.arange(2,11).reshape(3,3)
arr2 = np.matrix(arr2)
print(arr2)
print(arr2.shape)
print(type(arr2))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
<class 'numpy.matrix'>


3. How do you create a 2D array of shape (3, 3) with all elements as zeros?

In [18]:
arr1 = np.zeros((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


4. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [22]:
original_arr = np.ones((5,5))
print((original_arr))
original_arr[1:-1,1:-1]=0
print(original_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr2=arr1.reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [4]:
import numpy as np
arr1 = np.array([12, 13, 14, 15, 16, 17,18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
arr1 = arr1[::-1]
print(arr1)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


6. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [7]:
array_1 = np.zeros(10)
print(array_1)
array_1[6] = 11.
print(array_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [106]:
arr_1 = np.array([[ 1., 2],
                [ 3, 4],
                [ 5, 6]])
sec_arr = np.zeros((arr_1.shape[0]+2,arr_1.shape[1]+2))
#print(sec_arr)
sec_arr[1:-1,1:-1] = arr_1
#print(sec_arr)
arr2 = np.pad(arr_1,pad_width=1,mode="constant",constant_values=0)
print(arr2)


[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 5. 6. 0.]
 [0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]


In [22]:
check_arr = np.zeros((8,8))
check_arr[1::2,::2] = 1
check_arr[::2,1::2] = 1
print(check_arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [24]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8]
tuple1 = ((8, 4, 6), (1, 2, 3))
arr1 = np.array(list1)
print(arr1)
arr2 = np.array(tuple1)
print(arr2)

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [38]:
original_array = np.array([10, 20, 30])
val_to_append = np.array([40, 50, 60, 70, 80, 90])
original_array = np.append(original_array, val_to_append)
print(original_array)


[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]


In [43]:
original_array = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print(original_array)
print("Real Part ",original_array.real)
print("Imaginary Part ",original_array.imag)


[1.        +0.j         0.70710678+0.70710678j]
Real Part  [1.         0.70710678]
Imaginary Part  [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [53]:
arr_1 = np.array([1, 2, 3])
print("Size of the array: ",arr_1.size)
print(np.size(arr_1,axis=0))
print("Length of one array element in bytes: ",arr_1.itemsize)
print("Total bytes consumed by the elements of the array: ",arr_1.nbytes)

Size of the array:  3
3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [61]:
array_1 = np.array([ 0, 10, 20, 40, 60])
array_2 = np.array([10, 30, 40])

array_3 = np.intersect1d(array_1,array_2)
print(array_3)

[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [62]:
array_1 = np.array([0, 10, 20, 40, 60, 80])
array_2 = np.array([10, 30, 40, 50, 70, 90])
print(np.setdiff1d(array_1,array_2))

[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [63]:
array_1 = np.array([0, 10, 20, 40, 60, 80])
array_2 = np.array([10, 30, 40, 50, 70, 90])
print(np.setxor1d(array_1, array_2))

[ 0 20 30 50 60 70 80 90]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [94]:
array_a = np.array([1, 2])
array_b = np.array([4, 5])
print(array_a == array_b)
print(np.all(array_a < array_b))
print("a > b ",array_a > array_b)
print("a >= b ",array_a >= array_b)
print("a < b ",array_a < array_b)
print("a <= b ",array_a <= array_b)

[False False]
True
a > b  [False False]
a >= b  [False False]
a < b  [ True  True]
a <= b  [ True  True]


Write a Python program to save a NumPy array to a text file.

In [133]:
org_arr = np.array([[10, 20, 30], [20, 40, 50]])
np.savetxt("array.txt",org_arr,fmt = "%d")
load_data = np.loadtxt("array.txt",dtype = int)
print(load_data)

[[10 20 30]
 [20 40 50]]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [116]:
org_arr = np.array([[10, 20, 30], [20, 40, 50]])
org_arr = org_arr.flatten()
print(org_arr)

[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [100]:
arr1 = np.array([[2, 4, 6], [6, 8, 10]])
print(arr1.dtype)
arr2 = np.array(arr1, dtype=float)
print(arr2.dtype)
print(arr2)

int64
float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [101]:
arr1 = np.eye(3,3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [19]:
arr1 = np.zeros((4,3))
print(arr1)
arr1[1:,0] = arr1[2:,1] = arr1[-1,-1] = 1
print(arr1)
arr2 = np.zeros((4,3))
for i in range(1,4):
  arr2[i,:i] = 1
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [126]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
arr3 = np.concatenate((arr1,arr2),axis = 1)
print(arr3)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [9]:
import numpy as np
array_1 = np.array([0, 10, 20, 40, 60, 80])
array_1.flags.writeable = False
try :
  array_1[0] = 100
except ValueError as e:
  print(e)
print(array_1)

assignment destination is read-only
[ 0 10 20 40 60 80]


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [14]:
org_arr = np.arange(12).reshape(3,4)
print(org_arr)
new_arr = org_arr * 3
print(new_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [22]:
arr1 = np.array([[0, 1], [2, 3], [4, 5]])
print(type(arr1))
arr2 = list(arr1)
print(type(arr2))
arr1 = arr1.tolist()
print(arr1)
print(type(arr1))

<class 'numpy.ndarray'>
<class 'list'>
[[0, 1], [2, 3], [4, 5]]
<class 'list'>


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349 0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [25]:
array1 = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
0.35399976, 0.99469633, 0.0694458, 0.54711478])
array1 = np.round(array1, 3)
print(array1)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [35]:
arr_1 = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print(arr_1)
np.set_printoptions(suppress="True", precision= 3)
print(arr_1)

[   0.       1.6   1200.       0.235]
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [40]:
org_array = np.array([[10, 20, 30], [40, 50, 60]])
ext_array = np.array([[100], [200]])
org_array = np.append(org_array,ext_array,axis=1)
print(org_array)

[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [42]:
arr_1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr_1 = np.delete(arr_1, [0, 3, 4])
print(arr_1)

[ 20  30  60  70  80  90 100]
